# -*- coding: utf-8 -*-
"""hospital_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6cva02ag6CKRrq-JbSxxBT0_3mLebeA
"""

# RULE-BASED ENGINE (CORE & SAFE)
hospital_data = {
    "doctors": {
        "endocrinology": ["Dr. Ramesh Kumar", "Dr. Anita Sharma"],
        "cardiology": ["Dr. Suresh Rao"],
        "general": ["Dr. Meena Patel"]
    },
    "opd_timings": "9 AM to 5 PM (Monday to Saturday)",
    "floors": {
        "ground": "Reception, Pharmacy",
        "first": "OPD Clinics",
        "second": "Diagnostics & Labs",
        "third": "ICU"
    },
    "billing": {
        "payment_modes": ["Cash", "Card", "UPI", "Insurance"],
        "helpdesk": "Billing counter near reception"
    },
    "emergency": "Emergency department is open 24/7 on Ground Floor"
}

"""Purpose :

Handle deterministic hospital tasks:
1.Appointments
2.Doctor lookup
3.Billing info
4.Emergency guidance
5.Floor navigation
"""

#1.2 Rule-Based Response Function
def rule_based_response(user_query):
    query = user_query.lower()

    if "emergency" in query:
        return hospital_data["emergency"]

    if "appointment" in query:
        return f"Appointments are available during OPD hours: {hospital_data['opd_timings']}"

    if "doctor" in query:
        for dept in hospital_data["doctors"]:
            if dept in query:
                doctors = ", ".join(hospital_data["doctors"][dept])
                return f"Available doctors in {dept.title()}: {doctors}"
        return "Please specify the department to find a doctor."

    if "bill" in query or "payment" in query:
        modes = ", ".join(hospital_data["billing"]["payment_modes"])
        return f"Payment modes accepted: {modes}. For help, visit {hospital_data['billing']['helpdesk']}."

    if "floor" in query:
        response = "Hospital floor details:\n"
        for floor, details in hospital_data["floors"].items():
            response += f"{floor.title()} Floor: {details}\n"
        return response

    return None  # Pass to LLM

#HOSPITAL KNOWLEDGE BASE (FOR LLM)

hospital_knowledge = """
The hospital provides comprehensive medical services including OPD consultations,
diagnostic services, emergency care, pharmacy support, and billing assistance.

OPD clinics operate from 9 AM to 5 PM, Monday to Saturday.
Patients can book appointments at the reception or via the hospital chatbot.

The hospital has multiple departments including General Medicine, Cardiology,
Endocrinology, and Diagnostics.

Billing support includes insurance processing and multiple payment options.
"""

"""# 3 LLM CONVERSATIONAL ENGINE

Purpose:

Explain processes

Handle natural language

Answer FAQs

Guide patients politely
"""

#3.1 Mock LLM Function (Safe for Evaluation)
def llm_response(user_query):
    return (
        "I understand your question. "
        "Based on hospital information, I can guide you further. "
        "Please let me know if you want help with doctors, appointments, "
        "billing, or hospital navigation."
    )

#HYBRID ROUTER (THE HEART)
# 4.1 Hybrid Chatbot Function
def hybrid_chatbot(user_query):
    # Step 1: Try rule-based logic
    rule_response = rule_based_response(user_query)

    if rule_response:
        return rule_response

    # Step 2: Fall back to LLM
    return llm_response(user_query)

#5: TEST THE CHATBOT
queries = [
    "I want to book an appointment",
    "Which doctor should I see for diabetes?",
    "Where is the emergency department?",
    "How can I pay my hospital bill?",
    "Tell me about hospital services"
]

for q in queries:
    print("User:", q)
    print("Bot :", hybrid_chatbot(q))
    print("-" * 50)

import streamlit as st

st.set_page_config(page_title="Hospital Chatbot", layout="centered")

st.title("🏥 Hospital Assistant Chatbot")
st.caption("Hybrid Rule-Based + LLM Conversational System")

user_input = st.text_input("Ask your question:")

if user_input:
    response = hybrid_chatbot(user_input)
    st.success(response)

st.markdown("---")
st.markdown(
    "⚠️ **Disclaimer:** This chatbot provides informational assistance only "
    "and does not offer medical diagnosis or treatment."
)




